[project]
name = "vision"
version = "0.0"
requires-python = ">= 3.12"
dependencies = [
  # current Colab versions
  "numpy        == 2.0.*",
  "matplotlib   == 3.10.*",
  "scikit-image == 0.25.*",
  "pandas       == 2.2.*",
  "scipy        == 1.13.*",
  # project-specific libraries
  "watermark    == 2.4.*",
  "pyyaml       == 6.0.*",
  # local use only
  "jupyter",
  "nbdime",
  "nbstripout",
]
